services:
  company-compass:
    build: .
    container_name: company-compass
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=demo
      - APP_CONTEXT_PATH=
    networks:
      - global_tunnel_network

networks:
  global_tunnel_network:
    external: true